name: ci-test

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]

    runs-on: ubuntu-latest

    steps:
      - name: Setup Git repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log CI info
        run: |
          echo "system: $(uname -a)"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

      - run: npm ci
      - run: npm test
